Conductivity Probe Code
ShyavanS/McMaster_Chem-E_Car_24-25 pull request #1
Opened 2024-11-30 23:43 UTC by aroraa68

Added code for conductivity probe. Set a constant called EC_THRESH with some random value of 100 so it can be easily changed later

2024-12-01 00:32 UTC, ShyavanS commented
Looks good for the most part! I'd say remove the calibration line at the end though, we won't be needing that apart from initial calibration with the sensor before comp so it doesn't need to be in the competition code. Also, remove the extrra temperature sensor code from last year. Now that we're using the conductivity probe to stop the car, we don't need the extra if statemenet and temperature difference calculations. We're just using the raw temperature to correct for any temperature-based drift in the conductivity readings.

2024-12-01 00:34 UTC, ShyavanS requested changes
Looks good for the most part! I'd say remove the calibration line at the end though, we won't be needing that apart from initial calibration with the sensor before comp so it doesn't need to be in the competition code. Also, remove the extrra temperature sensor code from last year. Now that we're using the conductivity probe to stop the car, we don't need the extra if statement and temperature difference calculations. We're just using the raw temperature to correct for any temperature-based drift in the conductivity readings.

2024-12-01 00:34 UTC, ShyavanS commented on Car_Code/cheme_car_datalogging_codebase/cheme_car_datalogging_codebase.ino
>    if (tempChange >= tempDiff)
Also won't need this and it's accompanying code to calculate tempDiff & tempChange. Any references to those should be removed.

2024-12-01 00:34 UTC, ShyavanS commented on Car_Code/cheme_car_datalogging_codebase/cheme_car_datalogging_codebase.ino
> +  ec.calibration(voltage, temperatureC); // Calibration process
This won't be needed.

2024-12-01 00:43 UTC, aroraa68 commented
I removed the temperature change code and calibration code

2024-12-02 08:01 UTC, ShyavanS approved these changes
Looks good!

2024-12-06 17:16 UTC, aithihya-k approved these changes
looking good!

2024-12-06 17:24 UTC, merged