Tarnjots
ShyavanS/McMaster_Chem-E_Car_24-25 pull request #2
Opened 2024-12-04 21:47 UTC by TarnjotNijjer

Removed old IMU from Altium

2024-12-06 00:10 UTC, ShyavanS requested changes
You need to remove some extra traces and add a via. Now that the IMU is removed, there's no need to have the traces that I've added an orange slash over and in order to properly make the connection to the enable lines on the boost converter and motor driver, there has to be a via where I've circled. I would also suggest editing that long trace that would come off the via to just come out at a 45 deg angle instead of coming up and then out since those two resistors are no longer there and need to be connected (I've made a orange line that would indicate how the trace should look now. You'll also need to repour the ground plane polygon after making these changes so it doesn't have those holes in it where the resistor pads were & so it updates for the via placement.

See image below:
![image](https://github.com/user-attachments/assets/67bb5714-27a1-4869-9f66-4ed50af314e1)

2025-01-09 04:27 UTC, ShyavanS commented
You still need to conect the trace across the bottom and top layers since they can't connect without a via or pad to do so.
![image](https://github.com/user-attachments/assets/56071e70-5c6c-4af3-acd8-0fa30626a1eb)
Remove the remainder of the red top layer trace like in this picture and extend the blue bottom layer trace to follow the extension I drew in as a new orange trace and then repour the ground plane. Once you've done that, commit & push & re-request a review. Should be good to go at that point.

2025-01-10 03:44 UTC, TarnjotNijjer commented
Added my changes from the meeting.

2025-01-11 23:40 UTC, ShyavanS approved these changes
Looks good! Should be good to merge now!

2025-01-21 03:12 UTC, aithihya-k approved these changes
looks good to me as well!

2025-01-21 05:49 UTC, closed without merging